JavaScript-domasna-2
Goran94mkd/JS-HTML-CSS-Semos pull request #16
Opened 2020-11-24 03:11 UTC by Goran94mkd

2020-11-24 07:41 UTC, dpeshevski requested changes
@Goran94mkd размисли како да ги подобриш коментарите, доколку нешто не е јасно те молам слободно контактирај ме.

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/palindrome.js
> +const text = ['Македонија','анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];
Што ќе се случи во функцијата ако додадеме нов елемент во низата од data type number? На пример како нови елементи да бидет додадени 5225, 123454321, 998800, 3214.
Како ќе ја решиш грешката, и што треба да направиш за да го овозможува функцијата и овој тип?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/palindrome.js
> +  let allPalindromes = [];
Зошто е let? Не може да биде const, зарем?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/palindrome.js
> +      if (palindrome.replaceAll(' ', '') === text[i].replaceAll(' ', '')) {
Што прави оваа проверка? Што означува методата replaceAll?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +
Зошто е надвор од функцијата, тоест е дефинирано во global scope како globar variable?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +}
Линија 18 до 26 зошто се исто така во global scope, а не се сместени во функцијата?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +const obj = Object();
Да не ти недостасува new пред Object?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +const obj = Object();
Ти работи вака? И што означува ова Object()?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +const obj = Object();
Што прави линија 18.

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +console.log(arrFunction(secondString));
Зошто тука ја имаш извршено функцијата кога веднаш подолу ја инстанцираш?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +console.log(arrFunction(secondString));
Зарем console.log(evenStrings) нема да ни го даде истиот резултат на посакуван начин?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +	}
Што означува obj[evenStrings[i]]?

2020-11-24 07:41 UTC, dpeshevski commented on JavaScript-Domasna-2/words-even-characters.js
> +}
Размисли каде се случува ова сето што ти е дефинирано во global scope, треба да биде во рамки на функцијата evenStrings. Кога се извршува овој код? Дали има некое ограничување, односно треба ли да исполни некаков услов за да се изврши? Дали за сите податоци треба да се изврши?

2020-11-24 12:03 UTC, Goran94mkd commented on JavaScript-Domasna-2/palindrome.js
> +  let allPalindromes = [];
Може :) Работи и со const,
Всушност, и let и const се користат за декларирање на варијабла во block scope, за разлика од var која што повеќе се применува во function scope.

2020-11-24 12:37 UTC, Goran94mkd commented on JavaScript-Domasna-2/palindrome.js
> +      if (palindrome.replaceAll(' ', '') === text[i].replaceAll(' ', '')) {
Линија 5 - Ги проверува сите зборови од листата text едно по едно (поради i++), се до вредноста на text.length, односно помала од text.length

Линија 6 
- Со split се разделува array-от во на помали елементи, збор - по збор;
- со reverse ги чита од назад;
- со join сите елементи на array-ot ги враќа во string

Линија 7 - replaceAll методата во случајов се користи за бришење на празните места, при што првиот аргумент на методата ' '  (означува **што треба да се промени-избрише**) , додека вториот аргумент од методата означува (**што треба да го замени избришаното**.

2020-11-24 12:40 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +
Практично ми беше полесно да проверам како ќе изгледа низата после користење на методата split, па потоа во функцијата да се бараат зборовите со парен број карактери.
Инаку да, можеше да стои и внатре во функцијата и да се изврши истата проверка. :D

2020-11-24 12:45 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +}
Се обидував да ги вметнам двата "for loop-а" во истата функција, сметав дека е подобро како што ме имаш и ти советувано, ама не успеав :( 
На овој начин ми го даваше посакуваниот output и затоа вака го поставив.

Ќе се обидам да го вметнам вториот for loop во arrFunction функцијата.

2020-11-24 12:49 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +const obj = Object();
Корегирано :) 
Работи и вака, ама мора да стои new.
Strings can be objects (if defined with the new keyword) - во случајов формира нов празен стринг со new Object()

2020-11-24 12:59 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +console.log(arrFunction(secondString));
Да 
После const evenStrings = arrFunction(secondString); 
Со console.log(evenStrings) го дава истиот резултат. 

Благодарам :D

2020-11-24 13:06 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +	}
Во линија 22 ги означува зборовите со парен број карактери кои се повторуваат **повеќе од еднаш**
Во линија 24 ги означува зборовите со парен број карактери кои се повторуваат **еднаш**

2020-11-24 13:07 UTC, Goran94mkd commented on JavaScript-Domasna-2/palindrome.js
> +const text = ['Македонија','анаволимилована','дај ми една чаша полна со вино','радар','кајак', 'калабалак','нели не си ти сенилен','јадење и пиење дај','слушател','фудбал','музика'];
Сега ќе се обидам.

2020-11-25 19:30 UTC, Goran94mkd commented on JavaScript-Domasna-2/words-even-characters.js
> +}
@dpeshevski Успеав да ги вметнам двата for loop-a во функцијата. Види сега дали е океј?

2021-01-03 18:57 UTC, merged